### ISSUE TITLE
It crashes after global install on my mac (edit: on node V5.10.0)

### ISSUE THREAD

**Issue by iwangulenko** [omidfi/moro#14]
```
mac ~> which node
/Users/igu/.nvm/versions/node/v5.10.0/bin/node

mac ~> moro
/Users/mac/.nvm/versions/node/v5.10.0/lib/node_modules/moro/moro.js:13
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3````


```

**Comment by omidfi** [comment]
@iwangulenko  sorry to hear that. Seems like your node version (5.10.0) is too old for moro. Could you update to the current stable version? Or at least to version 6?

**Comment by omidfi** [comment]
@iwangulenko I just published a new version that should fix your problem. If you just update Moro by this command it should fix it now
```
npm install -g moro
```
