### ISSUE TITLE
After updating node moro doesn't work anymore

### ISSUE THREAD

**Issue by elutz** [omidfi/moro#163]
I updated nodejs to v8.9.4.
Now moro doesn't work:

```
moro hi 08:18

 💙  Moro \o/

Knex: run
$ npm install sqlite3 --save
Error: Cannot find module 'C:\Users\lutz.epperlein\AppData\Roaming\npm\node_modules\moro\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\lutz.epperlein\AppData\Roaming\npm\node_modules\moro\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Client_SQLite3._driver (C:\Users\lutz.epperlein\AppData\Roaming\npm\node_modules\moro\node_modules\knex\lib\dialects\sqlite3\index.js:75:12)
    at Client_SQLite3.initializeDriver (C:\Users\lutz.epperlein\AppData\Roaming\npm\node_modules\moro\node_modules\knex\lib\client.js:219:26)
    at Client_SQLite3.Client (C:\Users\lutz.epperlein\AppData\Roaming\npm\node_modules\moro\node_modules\knex\lib\client.js:113:10)
    at new Client_SQLite3 (C:\Users\lutz.epperlein\AppData\Roaming\npm\node_modules\moro\node_modules\knex\lib\dialects\sqlite3\index.js:58:20)
```
Reinstalling moro and sqlite3 didn't help.

**Comment by elutz** [comment]
Ok, found a solution.
I uninstalled `moro` and `sqlite3` and installed `moro` again. Now it works again.

Only one remark: after submitting `moro hi 08:18` I get only this:
```
$ moro hi 08:18

 💙  Moro \o/
```
In the past there was a message with some informations about the length of the working day and so on.

**Comment by elutz** [comment]
The problem with the truncated message happens only in cygwin bash on Windows. WIthin powershell it is fine,
