### ISSUE TITLE
Error on macOS

### ISSUE THREAD

**Issue by Isengo1989** [omidfi/moro#22]
```
/usr/local/lib/node_modules/moro/commands.js:96
const report = (args, options, logger = console.log, date = TODAY) => {

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/moro/moro.js:15:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

Any idea?

**Comment by omidfi** [comment]
Hi, thanks for reporting. It's about yoir node version. Could you update it to latest stable? Or at least version >= 6 ? 

I need to fix it later, but that solves yoir problem now.

**Comment by omidfi** [comment]
@Isengo1989  Please let me know what is your node version. 

I pushed an update that might fix your problem.
