### ISSUE TITLE
Crash when setting a break of 0 minutes

### ISSUE THREAD

**Issue by erwald** [omidfi/moro#29]
```sh
$ moro break 0
/Users/me/.nvm/versions/node/v7.5.0/lib/node_modules/moro/commands.js:68
  const duration = args.duration || CONFIG.BREAK_DEFAULT
                                          ^

TypeError: Cannot read property 'BREAK_DEFAULT' of undefined
    at Command.setBreak [as _action] (/Users/me/.nvm/versions/node/v7.5.0/lib/node_modules/moro/commands.js:68:43)
    at Command._run (/Users/me/.nvm/versions/node/v7.5.0/lib/node_modules/moro/node_modules/caporal/lib/command.js:395:25)
    at Program._run (/Users/me/.nvm/versions/node/v7.5.0/lib/node_modules/moro/node_modules/caporal/lib/program.js:133:16)
    at Program.parse (/Users/me/.nvm/versions/node/v7.5.0/lib/node_modules/moro/node_modules/caporal/lib/program.js:230:10)
    at Object.<anonymous> (/Users/me/.nvm/versions/node/v7.5.0/lib/node_modules/moro/moro.js:98:6)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
```

I wanted to say that I had no break on a day by setting the break to 0 minutes (maybe there's another way of doing that?), but it resulted in an error the log of which is pasted above.

**Comment by omidfi** [comment]
@erwald thanks for reporting :) 
It's fixed in the latest version. 
So updating by 
```
npm update -g moro
```
should fix it
